# Generated by Django 2.0.7 on 2018-08-03 15:20

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180802_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.utils.profile_image_upload_to, verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_day',
            field=models.PositiveIntegerField(choices=[(1, '1일'), (2, '2일'), (3, '3일'), (4, '4일'), (5, '5일'), (6, '6일'), (7, '7일'), (8, '8일'), (9, '9일'), (10, '10일'), (11, '11일'), (12, '12일'), (13, '13일'), (14, '14일'), (15, '15일'), (16, '16일'), (17, '17일'), (18, '18일'), (19, '19일'), (20, '20일'), (21, '21일'), (22, '22일'), (23, '23일'), (24, '24일'), (25, '25일'), (26, '26일'), (27, '27일'), (28, '28일'), (29, '29일'), (30, '30일'), (31, '31일')], default=3, verbose_name='생일'),
        ),
    ]
