# Generated by Django 2.0.7 on 2018-07-15 07:45

import apps.common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='태그')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='좋아요')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('category_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents_category_1', to='contents.Category', verbose_name='카테고리 1')),
                ('category_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents_category_2', to='contents.Category', verbose_name='카테고리 2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '콘텐츠',
                'verbose_name_plural': '콘텐츠',
            },
        ),
        migrations.CreateModel(
            name='ContentsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.common.utils.get_image_filename, verbose_name='이미지')),
                ('contents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents', verbose_name='콘텐츠')),
            ],
        ),
    ]
