# Generated by Django 2.0.7 on 2018-07-15 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
            ],
        ),
        migrations.RemoveField(
            model_name='contents',
            name='like',
        ),
        migrations.AddField(
            model_name='contents',
            name='update_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시각'),
        ),
        migrations.AddField(
            model_name='contentsimages',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='contents',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents', verbose_name='콘텐츠'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
