# Generated by Django 2.0.7 on 2018-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20180715_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요'),
        ),
    ]
