# Generated by Django 2.0.7 on 2018-07-15 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0004_auto_20180715_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
            ],
        ),
        migrations.RemoveField(
            model_name='contents',
            name='like',
        ),
        migrations.AlterField(
            model_name='contents',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='좋아요'),
        ),
        migrations.AddField(
            model_name='like',
            name='contents',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents', verbose_name='콘텐츠'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
