# Generated by Django 2.0.7 on 2018-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_auto_20180715_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='interest_count',
            field=models.PositiveIntegerField(default=0, verbose_name='찜한 횟수'),
        ),
        migrations.AddField(
            model_name='contents',
            name='interest_count',
            field=models.PositiveIntegerField(default=0, verbose_name='찜한 횟수'),
        ),
    ]
