# Generated by Django 2.0.7 on 2018-08-02 14:11

import apps.common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20180715_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentsimages',
            options={'verbose_name': '콘텐츠 사진', 'verbose_name_plural': '콘텐츠 사진'},
        ),
        migrations.AddField(
            model_name='contents',
            name='image',
            field=models.ImageField(default='d', upload_to=apps.common.utils.get_image_filename, verbose_name='이미지'),
            preserve_default=False,
        ),
    ]
