# Generated by Django 2.0.7 on 2018-07-15 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0007_auto_20180715_2346'),
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regist_dt', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.Category', verbose_name='카테고리')),
                ('contents', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents', verbose_name='콘텐츠')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '관심 목록',
                'verbose_name_plural': '관심 목록',
            },
        ),
    ]
