# Generated by Django 2.0.7 on 2018-07-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='contents',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Contents', verbose_name='콘텐츠'),
        ),
    ]
